### ISSUE TITLE
Line and Col counting error

### ISSUE THREAD

**Issue by pahaz** [adamfitzpatrick/tslint-stylish#2]
![image](https://cloud.githubusercontent.com/assets/1394025/9472465/f3c1fb44-4b6e-11e5-84fb-d0b238ead5b2.png)

After remove +1 in https://github.com/pteropus/gulp-tslint-stylish/blob/master/src/index.ts#L61-L62

![image](https://cloud.githubusercontent.com/assets/1394025/9472478/0e00ea6a-4b6f-11e5-91b1-3c014fffdb2b.png)

**Comment by ghost** [comment]
@pahaz Sorry for the delay here; my day job has been heavy.  I think I failed to check for outdated dependencies.  v1.0.4 is pushed up and should resolve the issue.  Please let me know if it continues to behave badly.

**Comment by pahaz** [comment]
Sorry, but this update is not solve my problem.

https://github.com/pteropus/gulp-tslint-stylish/blob/master/src/index.ts#L61-L62

**Comment by ghost** [comment]
I'm reopening this issue. The +1 in the code shoul definitely be required because tslint puts out position data that is zero indexed. I wasn't able to replicate a mismatch between report data and emitted error data using v1.0.4. Is it the emitted error that is correct, or the formatted report data?

As a quick potential fix, try running npm outdated and updating where appropriate. 

If that doesn't solve the issue, I wonder if you could provide me with a slimmed down example file (nothing proprietary, obviously), and version #s for chalk, lodash, log-symbols, text-table, gulp-tslint, gulp, npm, and nodejs. Most of those shouldn't have anything to do with this, but I'd like to cover my bases.

Finally, are you running this with gulp <task> or running an npm script? If it's the former, please be sure to give me your global gulp version.

**Comment by ghost** [comment]
@pahaz As I have not heard any more on this issue, I am closing it.
