### ISSUE TITLE
Need fullpath option

### ISSUE THREAD

**Issue by sagarvadodaria** [adamfitzpatrick/tslint-stylish#4]
We have a multi angular app scenario. Each app has its own app.ts. When i run stylish, it doesnt specify which app.ts has errors. I have created a pull request which adds the Option "fullPath" . If set to true, we can show the full path in console. 
![multiapp](https://cloud.githubusercontent.com/assets/5859358/10577340/292254ac-7688-11e5-88af-4ff96aac4386.JPG)

This is before the change 
![before](https://cloud.githubusercontent.com/assets/5859358/10577552/c93b4a42-7689-11e5-9793-ad97545a60b0.JPG)

This is after 
![after](https://cloud.githubusercontent.com/assets/5859358/10577551/c9394d46-7689-11e5-9e2a-e7256ab8bbf2.JPG)

**Comment by ghost** [comment]
@sagarvadodaria This looks great, and a very simple solution.  I will need to update some tests, but will integrate your changes soon.  Thank you for your contribution!

**Comment by sagarvadodaria** [comment]
Thanks a lot. Please update the npm so that we can consume it soon :) . And
yes you are correct, I was not sure of unit tests. Thanks for looking into
it.

**Comment by ghost** [comment]
@sagarvadodaria I have integrated your changes and published to npm.  I modified the implementation specifics for maintainability and testing purposes, but the end result is the same as your suggestion.  I don't know specifically which package you are using, because this repo feeds into two for the moment:
- gulp-tslint-stylish has been updated to version 1.1.1 (soon to be tagged deprecated)
- tslint-stylish has been updated to version 2.1.0-beta (intended to replace the gulp-exclusive implementation) 

Both now include the fullPath option.
